FROM node:20-alpine3.17

WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

EXPOSE 3004

# Start React development server
CMD ["npm", "start"]
